const data  = {
    Birds:[
        {//1
            name: "Acadian Flycatcher",
            species: "Empidonax virescens",
            date: "2008",
            status: "Endangered",
            location: "southern Ontario",
            photo: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/301816971/1800"
        },
        {//2
            name: "Barn Owl",
            species: "Tyto alba",
            date: "2008",
            status: "Endangered",
            location: "southern Ontario",
            photo: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/297342281/1800"
        },
        {//3
            name: "Golden eagle",
            species: "Aquila chrysaetos",
            date: "2008",
            status: "Endangered",
            location: "Hudson Bay Lowland in Ontario",
            photo: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/305364081/1800"
        },
        {//4
            name: "Henslow’s sparrow",
            species: "Ammodramus henslowii",
            date: "2008",
            status: "Endangered",
            location: "south of the Canadian Shield",
            photo: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/171447861/1800"
        },
        {//5
            name: "King rail",
            species: "Rallus elegans",
            date: "2008",
            status: "Endangered",
            location: "large wetlands bordering Lake St. Clair and along Lakes Erie and Ontario",
            photo: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/303143791/1800"
        },
        {//6
            name: "Kirtland’s warbler",
            species: "Setophaga kirtlandii",
            date: "2008",
            status: "Endangered",
            location: "southwestern Ontario at Canadian Forces Base Petawawa",
            photo: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/297030851/1800"
        },
        {//7
            name: "Loggerhead shrike",
            species: "Lanius ludovicianus",
            date: "2008",
            status: "Endangered",
            location: "the Carden Plain north of Lindsay, and the Napanee Limestone Plain",
            photo: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/302339191/1800"
        },
        {//8
            name: "Northern bobwhite",
            species: "Colinus virginianus",
            date: "2008",
            status: "Endangered",
            location: "southwest corner of Ontario, mostly on Walpole Island",
            photo: "https://cdn.download.ams.birds.cornell.edu/api/v1/asset/296736411/1800"
        }
    ],
    Mammals: [
        {
        name: "Algonquin Wolf",
            species: "Canus Lupus Lycaon",
            date: "2008",
            status: "Threatened",
            location: "Great Lakes Region",
            photo: "https://images.thestar.com/KNUcTK1yyqGW71Y_ekUSLp_Cr2c=/1280x1024/smart/filters:cb(1570529943334)/https://www.thestar.com/content/dam/thestar/opinion/commentary/2016/09/27/ontario-action-jeopardize-existence-of-algonquin-wolf/algonquin-wolf.jpg",
        },
        {
            name: "American Badger",
            species: "T.taxus",
            date: "2008",
            status: "endangered",
            location: "Northwest & Southwest Ontario",
            photo: "http://4.bp.blogspot.com/_xC0p-PBMm7U/SSentDDCwyI/AAAAAAAABqs/HkNNOY6J204/w1200-h630-p-k-no-nu/American+Badger+-+by+wikipedia+endangered+in+Ontario.jpg",
        },
        {
            name: "Beluga",
            species: "D. Leucas",
            date: "2008",
            status: "special concern",
            location: "Around the Hudson Bay",
            photo: "https://cdn.mos.cms.futurecdn.net/BewJL6fSPTKm4E3LngGyPN.jpg",
        },
        {
            name: "Caribou",
            species: "R. Tarandus",
            date: "2008",
            status: "Threatened",
            location: "Northern Forest and Eastern Lowlands",
            photo: "https://www.ctvnews.ca/polopoly_fs/1.4961127.1590791543!/httpImage/image.jpg_gen/derivatives/landscape_1020/image.jpg",
        },
        {
            name: "Easten Mole",
            species: "Scalopus",
            date: "2008",
            status: "Special Concern",
            location: "Extremely Southwest near Windsor",
            photo: "https://upload.wikimedia.org/wikipedia/commons/3/3e/ScalopusAquaticus.jpg",
        },
        {
            name: "Eastern Small-footed Myotis/Bat",
            species: "Myotis leibii",
            date: "2014",
            status: "Endangered",
            location: "Southern Ontario",
            photo: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Eastern_small-footed_bat.jpg",
        },
        {
            name: "Gray Fox",
            species: "U. cinereoargenteus",
            date: "2008",
            status: "Threatened",
            location: "West of Lake Superior",
            photo: "https://wxv73zw8wg-flywheel.netdna-ssl.com/wp-content/uploads/2018/12/Gray-Fox-1024x546.jpg",
        },
        {
            name: "Little Brown Myotis/Bat",
            species: "M. lucifigus",
            date: "2013",
            status: "Endangered",
            location: "Southern Ontario",
            photo: "https://www.gbbr.ca/wp-content/uploads/2019/03/Little-Brown-Myotis-%E2%80%93-Photo-credit-S.Dobbyn.jpg",
        },
        {
            name: "Mountain Lion (Cougar)",
            species: "P. concolor",
            date: "2008",
            status: "Endangered",
            location: "All of Ontario",
            photo: "https://www.nwf.org/-/media/NEW-WEBSITE/Shared-Folder/Wildlife/Mammals/mammal_mountain-lion_shutterstock_600x300.ashx",
        },
        {
            name: "Northern Myotis/Bat",
            species: "M. septentrionalis",
            date: "2013",
            status: "Endangered",
            location: "Forested Southern Ontario",
            photo: "https://www.gbbr.ca/wp-content/uploads/2019/03/Northern-Myotis-Photo-credit-S.-Dobbyn.jpg",
        },
        {
            name: "Polar Bear",
            species: "Ursus Maritimus",
            date: "2009",
            status: "Threatened",
            location: "Sea Ice of Thunder and James Bay",
            photo: "https://c402277.ssl.cf1.rackcdn.com/photos/18694/images/carousel_small/Polar_bear_with_cubs_in_Wapusk_WW266666.jpg?1582733801",
        },
        {
            name: "Tri-coloured Bat",
            species: "P. Subflavus",
            date: "2016",
            status: "Endangered",
            location: "Southern Ontario",
            photo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Tri-colored_bat_%28Perimyotis_subflavus%29_with_WNS_growth.JPG/220px-Tri-colored_bat_%28Perimyotis_subflavus%29_with_WNS_growth.JPG",
        },
        {
            name: "Wolverine",
            species: "G. gulo",
            date: "2008",
            status: "Threatened",
            location: "Northwest Forested Regions",
            photo: "https://defenders.org/sites/default/files/styles/meta_image/public/2019-04/wolverine_pixabay_header.jpg?itok=NJvvw4zI",
        },
        {
            name: "Woodland vole",
            species: "Microtus",
            date: "2008",
            status: "Special Concern",
            location: "Extremely South Ontario",
            photo: "https://animaldiversity.org/collections/contributors/phil_myers/ADW_mammals/Rodentia/pinetorum6732/large.jpg",
        },
    ],
}